### ISSUE TITLE
Occupancy only updates when in Home-App

### ISSUE THREAD

**Issue by DownForce17** [mpbzh/homebridge-plex#1]
Hi, after installing the plugin the automation is only triggered when I am in in homekit app or when updating favorites in control-center.

Thanks in advance

**Comment by mpbzh** [comment]
To be honest, I was not yet able to test the plugin yet – I did not expect that anyone would install the plugin so quickly after putting it online. 

I'll look into that and see what I can do about that. 

Do you have an Apple TV connected to your Homekit?

**Comment by DownForce17** [comment]
Hey, firstly thanks a lot for developing and sharing it! I saw, while submitting the issue that you just released it a couple of days ago. I am kinda new to that homebridge thing so i dont have that much experience. 

To your question, yes I do have an Apple TV 4 and it is my homekit hub. 

Thank you so much and let me know if I can help you identifying the issue. 

Simon

**Comment by nitaybz** [comment]
Hey @mpbzh 
great idea! great plugin!

I'm joining the request to add polling for status for the plugin.
I would suggest adding a "pollingInterval" field to the config and then make the plugin poll every x times and updateValue to homekit.

**Comment by pjvander** [comment]
What an awesome plugin!  Long-time Plex user and new Homebridge user; pulled the trigger on HomeKit as I just received a free Apple TV 4k.

I can confirm that the trigger doesn't fire until I switch back to the Home app.  

Thanks for the great plugin!

**Comment by mpbzh** [comment]
The dev branch feature some changes based on @nitaybz's contributions. I did not have the chance to test it yet, so if anyone could confirm that the changes do what they should, I can merge the code and publish a new version.

**Comment by cleverdevil** [comment]
I have installed the dev branch and can confirm that it fixes this issue, at least for me.

Great job, @mpbzh!

**Comment by mpbzh** [comment]
Thanks for testing! I'll release a new version then. 

And don't thank me, it's mainly @nitaybz' contribution, I just reformatted the code a bit
