### ISSUE TITLE
TypeError: Cannot read...'forEach'... 

### ISSUE THREAD

**Issue by L3x1c0n** [mpbzh/homebridge-plex#15]
I'm getting an error previously closed/discussed: 

\homebridge-plex\index.js:83
        data.Video.forEach(function (e) {
                   ^

TypeError: Cannot read property 'forEach' of undefined

I'm not sure where it's going wrong.

**Comment by Kimovitzh** [comment]
Same issue here.

**Comment by kingwoftam** [comment]
data.Video.forEach needs to be changed to data.Metadata.forEach

**Comment by Kimovitzh** [comment]
@kingwoftam 

It seems to work.

**Comment by Kimovitzh** [comment]
Oh, well.

...

/usr/lib/node_modules/homebridge-plex/index.js:83
        data.Metadata.forEach(function (e) {
                      ^

TypeError: Cannot read property 'forEach' of undefined
    at Request._callback (/usr/lib/node_modules/homebridge-plex/index.js:83:23)
    at Request.self.callback (/usr/lib/node_modules/homebridge-plex/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-plex/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-plex/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by L3x1c0n** [comment]
So is this patched? Is there a definitive resolution to this?

**Comment by Kimovitzh** [comment]
Still not working.

**Comment by eximiusvir** [comment]
Looks like kingwoftam's pull request is still pending...  [link](https://github.com/mpbzh/homebridge-plex/pull/16/files).

If you want to get up and running quickly, just modify your index.js (line 83) with his fix.  Worked for me.

**Comment by Kimovitzh** [comment]
@eximiusvir 

As you can see in my previously posts. It didn't work for me.
As soon as plex starts, the homebridge shuts down with the error:

```
/usr/lib/node_modules/homebridge-plex/index.js:83
data.Metadata.forEach(function (e) {
^

TypeError: Cannot read property 'forEach' of undefined

```

As you can see, line 83 is changed

**Comment by Kimovitzh** [comment]
Still no update?

I use this "plug-in" every day, som I'm very curious :)

**Comment by mpbzh** [comment]
Sorry, I currently don't have a running installation, that's why the issue drags along a bit...

You could help me by posting a (redacted) API response. 

So when you encounter the issue, open a browser and visit `http://<HOST>:32400/status/sessions?X-Plex-Token=<TOKEN>` (replacing`<HOST>` with the IP of your Plex server and `<TOKEN>` with your Plex token).

Then strip out any personal information and post the Content here.

**Comment by Kimovitzh** [comment]
I've updated my PLEX container on my server, updated all of my homebridge apps and changed data.Video.forEach to data.Metadata.forEach and then I tested it again and it seems to hold!

So it seems like the data.Metadata.forEach fixed it, this time.
I'll test it out the next days and give you my feedback then. 👌🏼

**Comment by donatelloth** [comment]
@mpbzh this is real. In JSON all information is stored in object "MetaData" and not in "Video" as in XML. Changing the variable from data.Video to data.Metadata fixes the situation.

**Comment by Qballjos** [comment]
Confirming that changing the data.Video to data.Metadata fixes the issue for now.

**Comment by iharosi** [comment]
Hey @mpbzh, would you mind to release this fix to npm?

**Comment by alexsalex** [comment]
Confirm, rename Video to Metadata fixed the issue.

**Comment by schmdt** [comment]
I can also confirm, changing index.js works. @mpbzh is there anything blocking an official NPM-Release?

**Comment by crashtestoz** [comment]
Is this plugin still being supported? There is another one that uses web hooks but you need PlexPass for it. I would prefer this method but I am reluctant to install if its not supported anymore.

**Comment by fetzu** [comment]
Just wanted to make a note for the author: the commit fixing this issue has been merged, but **you need to make a new release** in order for it to be pushed to npm.

Thank you for all your work !

**Comment by piccoloale** [comment]
> data.Video.forEach needs to be changed to data.Metadata.forEach

this works for me. 👍

**Comment by StefaanD** [comment]
Did work for me after changing it. But today it crashes on Metadata.forEach now also. Guess this project is all but abandoned because the initial issue was reported back in april last year and no real Solutions up until now. Oh well looking out for something better then.

**Comment by iharosi** [comment]
It looks like @mpbzh stopped maintaining this package so, I've forked the project and created a new npm package of it (including this fix): https://www.npmjs.com/package/homebridge-plex-v2
If you would like to participate in maintaining the package you are more than welcome!

**Comment by mpbzh** [comment]
@iharosi, thanks for taking on the project. As you all noticed, I unfortunately don't have time to maintain the project. Are you interested in working on the plugin as a collaborator in this repository?

**Comment by iharosi** [comment]
Hi @mpbzh ,
Sorry for the delay, I've been busy for a while. It would be great to work as a collaborator if I can help with that. ツ
Thanks!

**Comment by mpbzh** [comment]
Great to hear! I've sent you an invite link.

**Comment by iharosi** [comment]
Thanks!

**Comment by mpbzh** [comment]
This should be fixed. Please update `homebridge-plex` and reopen the issue if the error persists.
