### ISSUE TITLE
Getting 401 error

### ISSUE THREAD

**Issue by codyc1515** [mpbzh/homebridge-plex#20]
Hey there

I am getting a "Error getting state (status code 401): null" error. I have input a valid token, so not sure why this would be.

https://github.com/mpbzh/homebridge-plex/blob/b9795fba6fd73bd485eccee230d5a0e80abfeb80/index.js#L60

The server is not local so may be that's why.

Config looks like:

```
{
"accessory": "Plex",
"name": "Plex",
"plex_token": "xxxxxx",
"host": "XXX-XXX-XXX-XXX.929ed44XXXXXXXXX10de7d1017f33.plex.direct"
}
```

**Comment by iharosi** [comment]
Actually, I haven't tried with remote URL yet. And 401 means Unauthorized which is interesting. Are you sure your PMS is available all the time and there are no downtimes?

**Comment by codyc1515** [comment]
Yeah. I double checked going to the API called manually and it was giving the same error as well I think. It may well be a Plex configuration issue.

**Comment by iharosi** [comment]
Have you tried with IP address instead of Plex generated domain?

**Comment by codyc1515** [comment]
Looks like this project is abandoned. Closing.
