### ISSUE TITLE
Is it possible with a shared server???

### ISSUE THREAD

**Issue by JimmyEyeball** [mpbzh/homebridge-plex#21]
Is this possible with an external server that has been shared to me???

**Comment by JimmyEyeball** [comment]
Any Ideas.....

**Comment by iharosi** [comment]
It should work, yes.

**Comment by JimmyEyeball** [comment]
Are you able to point me to a previous example...

**Comment by iharosi** [comment]
Sorry, I've just looked into it and looks like it shoudn't work with shared server. It requires you to run your own Plex server as you need to have an `X-Plex-Token`.

**Comment by JimmyEyeball** [comment]
Would it be possible if I was supplied with the token from the external server???

**Comment by iharosi** [comment]
That means you need an admin token and a remote IP address which is a fix IP not a dynamic one. Haven't tried this scenario but I think it could work in case the required port is open.

**Comment by JimmyEyeball** [comment]
that should be doable as it is a friend's share... So just grab the token like a grabbed my own and an external IP for the Server and would it still be the same standard port also...

**Comment by iharosi** [comment]
In theory, yes it should work. Please let us know in case you made any success with this scenario! Thanks

**Comment by JimmyEyeball** [comment]
Great so just the same config as my local server but pointing to the external IP and use the supplied Token???

**Comment by iharosi** [comment]
That's the idea, yes.

**Comment by JimmyEyeball** [comment]
Great ill keep you posted .....

**Comment by JimmyEyeball** [comment]
All Working!!!  All tried and tested...

Required...

External IP of Remote/Shared Server
Plex Token From remote Server
Player Name you want to filter out
Upnp enabled on the router of the shared server

Pretty much the same as standard but just pointing to the remote server... The only thing I had to do was run them on separate instances as they didn't seem to like running on the same bridge...

**Comment by iharosi** [comment]
Awesome, thanks for letting us know!
