### ISSUE TITLE
Unable to get plex to appear in homekit

### ISSUE THREAD

**Issue by jnanes** [mpbzh/homebridge-plex#3]
I have the plugin installed and config.json configured. My logs show plex registering but the device never appears in homekit. any ideas? belows a snip of my json and logs

[2018-1-14 21:07:32] Registering platform 'homebridge-config-ui-x.config'
[2018-1-14 21:07:32] ---
[2018-1-14 21:07:32] Loaded plugin: homebridge-plex
[2018-1-14 21:07:32] Registering accessory 'homebridge-plex.Plex'
[2018-1-14 21:07:32] ---

        }
    ],
    "accessory": "Plex",
    "name": "PlexLivingRoom",
    "host": "10.5.5.2",
    "port": 32400,
    "plex_token": "XXXXXXXXXXXX REDACTED",
    "filter": [
        {
            "player": "Living Room"
        }
    ],

**Comment by mpbzh** [comment]
Do you have other plugins configured that are working?

Have you tried only starting homebridge with the Plex plugin?

**Comment by eximiusvir** [comment]
@mpbzh : I encountered this same issue and I'm wondering if it's a bug or simply a user education issue (at least in my case...).  Prior to installing **homebridge-plex**, I had installed **homebridge-nest-cam**, which worked without issue.

When I added the Plex configuration to my config.json, I restarted homebridge and assumed I needed to go into the iOS Home app, add a new accessory and add a new Accessory and manually enter the PIN again (assuming it would detect the new devices).  It did not.

I noted this post, removed the nest config from my config.json, tried again and it still didn't detect the plex instance.  I then removed the nest-cam plugin entirely, repeated the process above and again, it still did not work.

Finally, I iterated the username / MAC value for HomeBridge itself, and when I added a new bridge instance, it detected the homebridge-plex accessory.

I attempted to repeat the process of adding back in my nest cams, but was unsuccessful.

(noob questions): 

1. Are there limitations or specific steps required to host multiple homebridge plugins in a single homebridge process?

2. Is there a specific process to add additional accessories after you've added the homebridge instance to HomeKit (likely a question for the homebridge group, but if you have info from your experience, it would be appreciated)

**Comment by mpbzh** [comment]
As far as I understand, once `homebridge` is added to HomeKit, there is no need to manually add new devices. Just restart `homebridge` with the new config and you should be good to go. 

I'm closing this issue due to it's age and lack of activity.
