### ISSUE TITLE
Error getting state

### ISSUE THREAD

**Issue by neoTUGA** [mpbzh/homebridge-plex#7]
Hello,
Just installed the plugin (great idea BTW) im getting following error:

[PlexTV] Getting current state...
[PlexTV] Error getting state (status code 1): TypeError: The header content contains invalid characters

My configs are as follows:

 ```json
{
    "accessory": "Plex",
    "name": "PlexTV",
    "host": "192.168.0.1",
    "plex_token": "XXXXXXXXXXXX (redacted)",
    "filter": [
        {
            "user": "XXXXXXXXXXX (redacted)",
            "player": "TV UE55KU6000"
        }
    ]
}
```

Any ideas on were im going wrong? Thanks

**Comment by mpbzh** [comment]
You are trying to access your Plex installation on `192.168.0.1`. 

In home networks this is very often the IP address of the router – Are you sure that this is the IP address of the computer on which your Plex server is running?

You can easily verify this by opening `http://192.168.0.1:32400/status/sessions?X-Plex-Token= TOKEN` (replacing `TOKEN` with your Plex token) in your web browser.

The response you get should look something like this: 
```xml
<MediaContainer size="0"></MediaContainer>
```

Alternatively, if your Plex token is not valid, you should see something like "401 Unauthorized". You should then [obtain a new Plex token](https://support.plex.tv/hc/en-us/articles/204059436-Finding-an-authentication-token-X-Plex-Token).

Can you confirm that you get a valid result from the API?

**Comment by neoTUGA** [comment]
Everything was correct my routers / switches are 250 and up. Don’t know what was going on, got a new token and updated the conf. No errors anymore. 
Thanks anyway mate and great job. U have a fan here. ;)

**Comment by mpbzh** [comment]
Glad to hear your problem was fixed! Feel free to reopen the issue if you run into issues again.
