### ISSUE TITLE
[Plex] Error getting state (status code 1): TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["X-Plex-Token"]

### ISSUE THREAD

**Issue by noben78** [mpbzh/homebridge-plex#9]
Hi
can't get homebridge-plex to work. Everything looks OK in config file. Harmony remote Hub works fine in Homebridge.

Log:
[Plex] Getting current state...
[Plex] Error getting state (status code 1): TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["X-Plex-Token"]

I'm pretty sure I have the right Token

**Comment by mpbzh** [comment]
Please try the steps described [here](https://github.com/mpbzh/homebridge-plex/issues/7#issuecomment-362273279) to debug the token. 

Do you get a valid output?

**Comment by noben78** [comment]
Token works great, testing with:
 http://192.168.0.1:32400/status/sessions?X-Plex-Token= TOKEN (replacing TOKEN with my Plex)
Tested tree different token, all OK.
Tested on lokalhost. Running bridge och PMS on the same machine.

**Comment by noben78** [comment]
Tested with and without host and port in my config...same error message...

  "accessories": [{
      		"accessory": "Plex",
      		"name": "Plex",
          "plex_token": "​MYTOKEN",
          "host": "192.168.167.100",
          "port": 32400,
      		"filter": [{
      			"user": "MYUSER",
      			"player": "MYPLAYER"
      		}]
      	}],

**Comment by mpbzh** [comment]
There is a good chance that there is an issue with how the token is encoded to be sent to the server. 

What would help is posting the token here, however for you to securely do so you probably want to generate a new one for your server. You can read up about this here: https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/ (Getting a New Token)

This will require you to log in again on all your devices.

**Comment by noben78** [comment]
Thanks! 
I was trying out Atom for Mac. Deleted my config.json file and did it the old way in vi and now everything is up and running..
Big thanks!
btw, Plex for homebridge is logging every try in log file. Is it possible to turn off?

**Comment by mpbzh** [comment]
Glad to hear. 

Regarding the log output: Check issue #6
